### ISSUE TITLE
Version for macOS on Apple Silicon?

### ISSUE THREAD

**Issue by rossimariolee** [FrodeSolheim/fs-fuse#1]
Hi, could it be released a AppleSilicon or Universal version ?

**Comment by FrodeSolheim** [comment]
I don't have access to Apple Silicon hardware yet, and I'm probably not going to try to build something that I cannot run/test myself.

But the new good news are:

- The x86-64 version will probably run well on Apple M1 - I've heard the performance of Rosetta 2 is good, and this emulation is not very demanding.
- It is quite easy to compile yourself on macOS.

Compiling yourself:

- Install Xcode from the app store
- Install Homebrew from https://brew.sh

Then you can run the following commands from this repository in a terminal:

    fsplugin/installdeps
    fsplugin/bootstrap
    fsplugin/configure
    fsplugin/make

**Comment by Haroldo64** [comment]
Hi,
Brew system in not so clean and the app is not in the Application Folder but must be run from terminal... no so OSX friendly.
Please,  could someone add an unvversal binary app ?
bye

**Comment by PakkunKinoppi** [comment]
Yeah ..brew does not create an app in the application folder. Orrible system for mac users
Better an arm version for Apple Silicon, that's future

**Comment by FrodeSolheim** [comment]
I still haven't got Apple silicon hardware. The latest version in git contains scripts for building with all dependencies, independent of libraries from homebrew.

    fsdeps/build
    fsdeps/use fsbuild/bootstrap
    fsdeps/use fsbuild/configure
    fsdeps/use fsbuild/build
    fsdeps/use fsbuild/bundle
    fsdeps/use fsbuild/archive

It might require a few packages from (brew install autoconf automake dos2unix) but only for the build process.

(To make a distributable version, it also needs to be signed and notarized. There are helper scripts for that as well, but it also requires an Apple developer account).

Other than that, I suppose the x86-64 version should work quite well on M1. The emulation isn't very demanding, so the Rosetta2 translation layer "penalty" should presumably not be that great.

**Comment by FrodeSolheim** [comment]
There is now a build for Apple silicon: https://github.com/FrodeSolheim/fs-fuse/releases/tag/v1.0.14-master

**Comment by PakkunKinoppi** [comment]
THANK YOU !  It's great !
:cupid:

**Comment by Alessandro1970** [comment]
Hello,
this is really great news.
Fuse is the best emulator for Zx and I have been using it for many years.
A fuse lacks only an on-screen virtual keyboard to use with the mouse "point & click" ... as there is in the VirtualC64 or in the vAmiga on macOS; this Virtual keyboard would be a spectacular implementation, just for a computer that had many commands written on the key-caps and a neophyte would approach it with less fear ...
Thank you

**Comment by Haroldo64** [comment]
wonderful news, thank you
